[features]
resolution = true
skip-lint = false

[programs.localnet]
data_arbiter = "9vZy3wDuyeWiajhxG8WCFxHMXAijrzmCTbmA44XaV7cg"

[programs.devnet]
data_arbiter = "9vZy3wDuyeWiajhxG8WCFxHMXAijrzmCTbmA44XaV7cg"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
